services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - TZ=Asia/Shanghai
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: kyeo
      POSTGRES_PASSWORD: K572375k
      POSTGRES_DB: svm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: